services:
  db:
    image: postgres
    container_name: postgres_db_jirarush
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_jirarush
    volumes:
      - ./resources:/app/./resources
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_jirarush
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/static:/opt/jirarush/resources/static
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
    driver: local